general:
  report_frequency: 1
  enable_wandb_hook: true
model:
  type: torchscript
  parameters:
    filename: cans_fcn.pt
loss:
  type: MSE
optimizer:
  type: adam
  parameters:
    learning_rate: 1e-3
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0
    eps: 1e-8
    amsgrad: 0
lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 60000
